server:
  port: 9001
  context-path: /beerhouse

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:craftbeer;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update

flyway:
  url: jdbc:h2:mem:craftbeer
  schemas:
  - craftbeer
  user: sa
  password: 