spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:craftbeer;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true